# =============================================================================
# Corvid OS — finished module
# =============================================================================
restartNowMode:      user-unchecked
restartNowCommand:   "systemctl -i reboot"

# Show a "restart now" option; do not force it.
notifyOnFinished:    false
