#!/bin/sh
# Corvid OS -- provisioning/remaster-uefi.sh
# ===========================================================================
# Turns live-build 3.0's output ISO (which has NO El Torito boot record) into a
# UEFI-bootable Corvid ISO. Called automatically by auto/build; can also be run
# by hand against an existing data ISO.
#
#   Usage: provisioning/remaster-uefi.sh [input.iso] [output.iso]
#     input.iso   the live-build data ISO; auto-detected if omitted
#     output.iso  the bootable result; default corvid-amd64.iso
#
# How it works: build a standalone GRUB x86_64-efi image (BOOTX64.EFI) that
# searches the ISO for /boot/grub/grub.cfg and hands off to it, drop it into a
# small FAT EFI System Partition image, then re-master the input ISO adding that
# ESP as an El Torito EFI boot entry. The result is UEFI-only, which Ventoy and
# modern hardware boot fine.
#
# Requires (all on a normal Ubuntu build host): grub-common (grub-mkstandalone),
# grub-efi-amd64-bin (the x86_64-efi modules), dosfstools (mkfs.vfat), mtools
# (mmd/mcopy), xorriso.
# ===========================================================================
set -e

IN="${1:-}"
OUT="${2:-corvid-amd64.iso}"

# Auto-detect the live-build data ISO if not given.
if [ -z "$IN" ]; then
	for _c in live-image-amd64.hybrid.iso corvid-amd64.hybrid.iso binary.hybrid.iso chroot/binary.hybrid.iso; do
		if [ -f "$_c" ]; then IN="$_c"; break; fi
	done
fi
if [ -z "$IN" ] || [ ! -f "$IN" ]; then
	echo "remaster-uefi: no input ISO found (pass one explicitly)" >&2
	exit 1
fi

for _t in grub-mkstandalone mkfs.vfat mmd mcopy xorriso; do
	command -v "$_t" >/dev/null 2>&1 || { echo "remaster-uefi: missing tool '$_t'" >&2; exit 1; }
done

echo "==> remaster-uefi: input=$IN  output=$OUT"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT INT TERM

# Embedded GRUB config: locate the ISO root by a known file, then load its
# real /boot/grub/grub.cfg (generated by live-build with the boot entries).
cat > "$WORK/embed.cfg" <<'EOF'
insmod part_gpt
insmod part_msdos
insmod fat
insmod iso9660
insmod search
insmod normal
insmod configfile
search --set=root --file /boot/grub/grub.cfg
set prefix=($root)/boot/grub
configfile /boot/grub/grub.cfg
EOF

grub-mkstandalone -O x86_64-efi -o "$WORK/BOOTX64.EFI" \
	"boot/grub/grub.cfg=$WORK/embed.cfg" \
	--modules="part_gpt part_msdos fat iso9660 search search_fs_file normal configfile linux ls echo test all_video gfxterm"

# Small FAT EFI System Partition holding /EFI/BOOT/BOOTX64.EFI.
dd if=/dev/zero of="$WORK/efi.img" bs=1M count=12 status=none
mkfs.vfat -n CORVIDEFI "$WORK/efi.img" >/dev/null
mmd -i "$WORK/efi.img" ::/EFI ::/EFI/BOOT
mcopy -i "$WORK/efi.img" "$WORK/BOOTX64.EFI" ::/EFI/BOOT/BOOTX64.EFI

# Re-master: copy the input ISO, add BOOTX64.EFI into the tree, append the ESP
# and register it as the El Torito EFI boot image.
xorriso -indev "$IN" -outdev "$OUT" \
	-volid CORVID \
	-map "$WORK/BOOTX64.EFI" /EFI/BOOT/BOOTX64.EFI \
	-append_partition 2 0xef "$WORK/efi.img" \
	-boot_image any efi_path=--interval:appended_partition_2:all:: \
	-boot_image any partition_table=on

echo "==> remaster-uefi: wrote $OUT"
xorriso -indev "$OUT" -report_el_torito plain 2>&1 | grep -iE 'El Torito boot img' || \
	echo "remaster-uefi: WARNING - could not confirm El Torito EFI entry" >&2
